apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/appsmith.update-strategy: newest-build
    argocd-image-updater.argoproj.io/image-list: appsmith=index.docker.io/appsmith/appsmith-ee:latest,
    argocd-image-updater.argoproj.io/appsmith.force-update: "true"
spec:
  destination:
    namespace: supabase
    server: 'https://80758D88513C44864E837A308D541B3C.gr7.ap-south-1.eks.amazonaws.com'
  source:
    repoURL: 'https://helm-ee.appsmith.com'
    chart: appsmith
    targetRevision: "3.0.11"
    helm:
      values: |
        mongodb:
          enabled: false
        redis:
          enabled: false
        postgresql:
          enabled: false
        _image:
          registry: index.docker.io
          repository: appsmith/appsmith-ee
          pullPolicy: Always
        image:
          tag: latest
        ingress:
          enabled: true
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:391311798816:certificate/6482c498-2538-4bf6-bcae-58c279a1b5ae
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/limit-rps: "15"
          ingressClassName: nginx
          hosts:
            - host: "supabase.demo.appsmith.com"
              paths:
              - path: "/"
                pathType: Prefix
          className: "nginx"
        resources:
          limits:
             memory: 3000Mi
          requests:
             cpu: 1m
             memory: 1Mi
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 1
          targetCPUUtilizationPercentage: 5
        persistence:
          enabled: true
          storageClass: "efs-dp-appsmith"
          efs:
            enabled: true
            driver: efs.csi.aws.com
            volumeHandle: fs-0e392e1595e5d5175:/dp/supabase
        applicationConfig:
          APPSMITH_MONGODB_URI: "mongodb+srv://appsmithadmin:W58w5yCN6ZY5Y42A@appsmith-infra-test-clu.zljea.mongodb.net/supabase?retryWrites=true&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000&authSource=admin"
          APPSMITH_SENTRY_DSN: "https://abf15a075d1347969df44c746cca7eaa@o296332.ingest.sentry.io/1546547"
          APPSMITH_SENTRY_ENVIRONMENT: test
          APPSMITH_CUSTOMER_PORTAL_URL: "https://release-customer.appsmith.com"
          APPSMITH_LICENSE_KEY: "87E0F1-7BF40C-6CC388-C960C5-FF7311-V3"
project: default
syncPolicy:
    automated: {}
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true